### ISSUE TITLE
 findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by SeyyedKhandon** [iamhosseindhv/notistack#399] opened 2021-06-28 05:08 UTC
Here is the error which I got when using notistack, when the snack bar disappears this error will be printed out in browser console:

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

**Comment by iamhosseindhv** [comment] 2021-07-14 01:21
Duplicate of #257 #345

**Closed by iamhosseindhv** 2021-07-14 01:21 UTC
