### ISSUE TITLE
TS Error: SnackbarProvider cannot be used as a JSX component

### ISSUE THREAD

**Issue by ryancrunchi** [iamhosseindhv/notistack#485] opened 2022-04-27 13:01 UTC
Seems there is a conflict in types between `@types` versions used. I use `"@types/react": "^18.0.8"` and `"@types/react-dom": "^18.0.0"` while notistack and/or mui use `"@types/react": "^16.8.6 || ^17.0.0"` or `"@types/react": "^16.9.23"`

## Expected Behavior

No compiler error

## Current Behavior

Compiler error:
```
'SnackbarProvider' cannot be used as a JSX component.
  Its instance type 'SnackbarProvider' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("node_modules/@mui/types/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
          Type '{}' is missing the following properties from type 'ReactPortal': key, children, type, props
```

## Steps to Reproduce

Link:

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v2.0.4  |
| React        | ^18.1.0 |
| @types/react | ^18.0.8 |
| @types/react-dom | ^18.0.0 |

**Comment by manfe** [comment] 2022-04-29 13:37
Same here with `react@17.0.2` and `@types/react@17.0.44`

**Comment by luisr-carrillo** [comment] 2022-05-06 15:28
Same here with `react@17.0.2` and `@types/react@17.0.33`. Hope the [PR](https://github.com/iamhosseindhv/notistack/pull/486) can fix it. 🙏

**Comment by NHarviel** [comment] 2022-05-06 15:38
I was getting this same compile error I updated my @types/react to 18.0.8 and I am no longer getting the compilation error.

**Comment by ryancrunchi** [comment] 2022-05-06 15:49
I solved by setting in package.json
```
  "resolutions": {
    "@types/react": "18.0.8",
    "@types/react-dom": "18.0.3"
  }
```

**Comment by luisr-carrillo** [comment] 2022-05-06 19:12
> I solved by setting in package.json
> 
> ```
>   "resolutions": {
>     "@types/react": "18.0.8",
>     "@types/react-dom": "18.0.3"
>   }
> ```

It works with that config. Thank you! 🙏

**Comment by iamhosseindhv** [comment] 2022-05-11 23:49
Thanks for reporting and I'm glad there's some solution for this. I've been unable to reproduce, so if you could provide one, I'll reopen this issue.

**Comment by iamhosseindhv** [comment] 2022-05-11 23:49
Thanks for reporting and I'm glad there's some solution for this. I've been unable to reproduce, so if you could provide one, I'll reopen this issue.

**Comment by iamhosseindhv** [comment] 2022-05-16 22:48
As mentioned above, I'd need a reproduction sandbox to investigate this

**Comment by hangaoke1** [comment] 2022-05-17 11:47
/node_modules/notistack/dist/index.d.ts
```
export class SnackbarProvider extends React.Component<SnackbarProviderProps> {
    enqueueSnackbar: ProviderContext['enqueueSnackbar'];

    closeSnackbar: ProviderContext['closeSnackbar'];
}
```

there is no render function in declaration file

**Comment by hangaoke1** [comment] 2022-05-17 11:57
> 
/node_modules/notistack/dist/index.d.ts
```ts
export class SnackbarProvider extends React.Component<SnackbarProviderProps> {
    enqueueSnackbar: ProviderContext['enqueueSnackbar'];

    closeSnackbar: ProviderContext['closeSnackbar'];
}
```
there is no render function in declaration file

```ts
export class SnackbarProvider extends React.Component<SnackbarProviderProps> {
    enqueueSnackbar: ProviderContext['enqueueSnackbar'];

    closeSnackbar: ProviderContext['closeSnackbar'];

    render(): ReactNode;
}
```
fix the problem

the reason is when you extends React.Compoent there is no render function declaration
![image](https://user-images.githubusercontent.com/19623160/168804775-25546152-6961-4aa2-943e-72802f4ced40.png)

**Comment by LorhanSohaky** [comment] 2022-05-18 12:44
Same error

**Comment by outragedhuman** [comment] 2022-05-25 20:49
Same error with:

```
"react": "^17.0.2",
"@types/react": "^17.0.35",
```

Adding the suggested `resolutions` to package.json breaks my app in other ways and doesn't resolve the TS error.

FWIW this was never working for me, I just tried adding notistack to my app Today. I also just tried replicating in Codesandbox but it was struggling to find react-dom 17.0.2 so I didn't get anywhere.

If I manually patch `/node_modules/notistack/dist/index.d.ts` as described by @hangaoke1, it works. Is it possible to get a fix for that? Since I can't get a Codesandbox working I could provide you with a test branch from my app if that would help?

**Comment by bibixx** [comment] 2022-06-01 21:55
I am currently facing the same issue using react **17.0.2**. I have tried to reproduce it in CodeSandbox but the issue didn't appear there! From my small investigation it seems like the issue is `yarn`.
@iamhosseindhv I have created a reproduction repository [bibixx/notistack-issue-485](https://github.com/bibixx/notistack-issue-485) that uses `yarn` (also there's a branch using `npm` where the whole thing seems to work just fine)

For the quick path you can create a `.d.ts` file (like `notistack.d.ts`) and augment the module with:
```ts
import { SnackbarProvider as SnackbarProviderBase } from 'notistack';

declare module 'notistack' {
  export interface SnackbarProvider extends SnackbarProviderBase {
    render(): ReactNode;
  }
}

```

**Comment by outragedhuman** [comment] 2022-06-01 22:15
I can confirm my affected project uses `yarn`.

**Comment by dryhurst** [comment] 2022-07-05 13:22
also using `yarn`. also react `17.0.2`

i was able to fix the issue by making sure the following packages were aligned: 

`react`, `@types/react`, and `@types/react-dom` 

all set to version `17.0.2`

i also created the file `notistack.d.ts` and put `declare module 'notistack';` in the file. 

and as if by magic, the issue resolved. 

not sure if this is the preferred solution but it worked for me, for now.

**Comment by gjoseph** [comment] 2022-07-20 10:48
> also using `yarn`. also react `17.0.2`
> 
> i was able to fix the issue by making sure the following packages were aligned:
> 
> `react`, `@types/react`, and `@types/react-dom`
> 
> all set to version `17.0.2`
> 
> i also created the file `notistack.d.ts` and put `declare module 'notistack';` in the file.
> 
> and as if by magic, the issue resolved.
> 
> not sure if this is the preferred solution but it worked for me, for now.

that does nothing but override the type declaration of notistack with an empty one.

The real fix is highlighted by @hangaoke1 above -- which is something you can do in your local `notistack.d.ts` too, but ideally it should be fixed upstream in this package

**Comment by Rich79923** [comment] 2022-08-01 11:02
Any update for when this will be fixed?

**Comment by C0DESTR0NG** [comment] 2022-08-08 22:25
> Any update for when this will be fixed?

I also need a fix for this. Following!

**Comment by w90** [comment] 2022-08-25 13:48
For Typescript and React users, a possible solution:

```
import providers, { Provide } from 'react-manage-providers'
import { SnackbarProvider } from 'notistack'
import { SNACKBAR_OPTIONS, QUERY_CLIENT_OPTIONS, QueryClientProvider } from '@company/utils-general'

providers.push(SnackbarProvider, SNACKBAR_OPTIONS)
providers.push(QueryClientProvider, QUERY_CLIENT_OPTIONS)

export const MasterProvider = Provide
```
```
export const App = () => (
  <MasterProvider>
    <CssBaseline />

    <BrowserRouter>
      <RootRouter />
    </BrowserRouter>
  </MasterProvider>
)
```

**Closed** 2022-10-15 15:55 UTC

**Comment by iamhosseindhv** [comment] 2022-10-15 16:05
The fix for this is published as `v2.0.7`. Sorry for the tardy fix. Appreciate if you could confirm the fix has resolved the issue.

**Comment by jordansexton** [comment] 2022-10-15 22:09
Just updated to 2.0.7 and getting some new errors:

```
node_modules/.pnpm/notistack@2.0.7_o5fu5zzztezljyppmu7zljxb6q/node_modules/notistack/dist/index.d.ts:263:15 - error TS2304: Cannot find name 'ReactNode'.

263     render(): ReactNode;
                  ~~~~~~~~~

node_modules/.pnpm/notistack@2.0.7_o5fu5zzztezljyppmu7zljxb6q/node_modules/notistack/dist/index.d.ts:274:76 - error TS2724: 'global.JSX' has no exported member named 'element'. Did you mean 'Element'?

274 export declare const SnackbarContent: (props: SnackbarContentProps) => JSX.element
```

Resolved dependencies:
```
react        = 18.2.0
@types/react = 18.0.21
```

**Comment by jordansexton** [comment] 2022-10-15 22:12
First error is because this line references a nonexistant import:
https://github.com/iamhosseindhv/notistack/blob/9ec749b28e4682eb859372fa3529db1eceb4b061/src/index.d.ts#L267

This should be `React.ReactNode` consistent with other references.

**Comment by jordansexton** [comment] 2022-10-15 22:13
And the second type `JSX.element` should maybe be `React.ReactElement`?

**Comment by jordansexton** [comment] 2022-10-15 22:16
PR to fix: https://github.com/iamhosseindhv/notistack/pull/520

**Comment by iamhosseindhv** [comment] 2022-10-16 14:00
The fix is published as `v2.0.8`.

**Comment by outragedhuman** [comment] 2022-10-17 19:12
> The fix is published as `v2.0.8`.

Should this fix resolve the issue for React 17, or just React 18?

I'm running 17.0.2 and still seeing this on Notistack 2.0.8:

    "react": "^17.0.2",
    "notistack": "^2.0.8",


```
 ERROR(TypeScript)  'SnackbarProvider' cannot be used as a JSX component.
  Its instance type 'SnackbarProvider' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/Users/nbowers/git/upnorthcoding/projectJovian/node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
 FILE  /Users/nbowers/git/upnorthcoding/projectJovian/src/index.tsx:14:6

    12 |     <CssBaseline />
    13 |     {/* TODO: Is it possible to lower this in the app's heirarchy? It could lead to less un-neccesary renders */}
  > 14 |     <SnackbarProvider maxSnack={MaximumSnackbarMessages}>
       |      ^^^^^^^^^^^^^^^^
    15 |       <App />
    16 |     </SnackbarProvider>
    17 |   </React.StrictMode>,

[TypeScript] Found 1 error. Watching for file changes.
```

**Comment by EvanVujcec** [comment] 2022-11-03 16:47
> > The fix is published as `v2.0.8`.
> 
> Should this fix resolve the issue for React 17, or just React 18?
> 
> I'm running 17.0.2 and still seeing this on Notistack 2.0.8:
> 
> ```
> "react": "^17.0.2",
> "notistack": "^2.0.8",
> ```
> 
> ```
>  ERROR(TypeScript)  'SnackbarProvider' cannot be used as a JSX component.
>   Its instance type 'SnackbarProvider' is not a valid JSX element.
>     The types returned by 'render()' are incompatible between these types.
>       Type 'React.ReactNode' is not assignable to type 'import("/Users/nbowers/git/upnorthcoding/projectJovian/node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.
>         Type '{}' is not assignable to type 'ReactNode'.
>  FILE  /Users/nbowers/git/upnorthcoding/projectJovian/src/index.tsx:14:6
> 
>     12 |     <CssBaseline />
>     13 |     {/* TODO: Is it possible to lower this in the app's heirarchy? It could lead to less un-neccesary renders */}
>   > 14 |     <SnackbarProvider maxSnack={MaximumSnackbarMessages}>
>        |      ^^^^^^^^^^^^^^^^
>     15 |       <App />
>     16 |     </SnackbarProvider>
>     17 |   </React.StrictMode>,
> 
> [TypeScript] Found 1 error. Watching for file changes.
> ```

I'm also having this issue on React 17.0.1 (environment on this project does not allow higher than 17.0.1)
Upgrading the types to 18 fixes the build error but still shows a type error in editor which can be suppressed 😐.

**Comment by kidqn** [comment] 2022-11-04 04:49
> 

Please upgrade React to 17.0.2

add ```declare module 'notistack'``` to react-app-env.ts

package.json:
    ```"react": "^17.0.2",
    "notistack": "2.0.8",
    "react-dom": "^17.0.2",
    "@types/react": "^17.0.52",
    "@types/react-dom": "^17.0.18",```

**Comment by kidqn** [comment] 2022-11-04 04:51
> > > The fix is published as `v2.0.8`.
> > 
> > 
> > Should this fix resolve the issue for React 17, or just React 18?
> > I'm running 17.0.2 and still seeing this on Notistack 2.0.8:
> > ```
> > "react": "^17.0.2",
> > "notistack": "^2.0.8",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >  ERROR(TypeScript)  'SnackbarProvider' cannot be used as a JSX component.
> >   Its instance type 'SnackbarProvider' is not a valid JSX element.
> >     The types returned by 'render()' are incompatible between these types.
> >       Type 'React.ReactNode' is not assignable to type 'import("/Users/nbowers/git/upnorthcoding/projectJovian/node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.
> >         Type '{}' is not assignable to type 'ReactNode'.
> >  FILE  /Users/nbowers/git/upnorthcoding/projectJovian/src/index.tsx:14:6
> > 
> >     12 |     <CssBaseline />
> >     13 |     {/* TODO: Is it possible to lower this in the app's heirarchy? It could lead to less un-neccesary renders */}
> >   > 14 |     <SnackbarProvider maxSnack={MaximumSnackbarMessages}>
> >        |      ^^^^^^^^^^^^^^^^
> >     15 |       <App />
> >     16 |     </SnackbarProvider>
> >     17 |   </React.StrictMode>,
> > 
> > [TypeScript] Found 1 error. Watching for file changes.
> > ```
> 
> I'm also having this issue on React 17.0.1 (environment on this project does not allow higher than 17.0.1) Upgrading the types to 18 fixes the build error but still shows a type error in editor which can be suppressed 😐.

> 

Please upgrade React to 17.0.2

add ```declare module 'notistack'``` to react-app-env.ts

package.json:

-  "react": "^17.0.2",
- "notistack": "2.0.8",
- "react-dom": "^17.0.2"
-  "@types/react": "^17.0.52"
- "@types/react-dom": "^17.0.18"

**Comment by garrett-wombat** [comment] 2022-11-18 05:45
Im having the same issue after updating to `react 18.2.0` and `react-dom 18.2.0`.

I had to just just ignore the ts error
```
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
```

Has anyone found a solution to this?

**Comment by chrishawn** [comment] 2022-12-03 22:04
yeah this isnt fixed in React 17.02 and notistack 2.0.8 using yarn at least

**Comment by chrishawn** [comment] 2022-12-04 03:39
so the solution seems to be update to latest notistack 2.0.8
then do
```
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
```
    
 even if you leave these at 17
 ```
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
```

**Comment by mbsc26** [comment] 2023-03-12 23:07
> so the solution seems to be update to latest notistack 2.0.8 then do
> 
> ```
>     "@types/react": "^18.0.26",
>     "@types/react-dom": "^18.0.9",
> ```
> 
> even if you leave these at 17
> 
> ```
>    "react": "^17.0.2",
>    "react-dom": "^17.0.2",
> ```

Saved my life. Thank you.

**Comment by ninjarogue** [comment] 2023-05-22 09:59
We're having the same issue here as well...

**Comment by AlbinoGeek** [comment] 2023-05-25 18:33
This still happens.

**Comment by aprilmintacpineda** [comment] 2023-06-05 08:12
Just encountered this with:

```
"@types/react": "18.2.8",
"@types/react-dom": "18.2.4"
```

**Comment by AlbinoGeek** [comment] 2023-06-05 10:14
In my case, it was fixed by **deleting yarn.lock** and doing `yarn install` again. Something got funky with the versions after a merge messed with the lockfile.

**Comment by ninjarogue** [comment] 2023-06-09 13:19
I think this is related to #562. Could someone please fix this already?

**Comment by nouman91** [comment] 2023-07-14 17:26
I am getting this issue as well. I tried the @bibixx solution but unfortunately, it's not working for me.

**Comment by nouman91** [comment] 2023-07-14 20:07
Any help would definitely be appreciated in this. My dependencies:

`react: 17.0.2
react-redux: 17.0.2
noistack: 3.0.1`

**Comment by ammoradi** [comment] 2023-09-04 06:30
Same issue here:

```
"@types/react": "^18.2.12",
"@types/react-dom": "^18.2.5",

"notistack": "3.0.1",
```

**Comment by AdedigbaOluwad1** [comment] 2023-09-04 06:32
I don't know what the maintainers are looking at. They should've merged
this PR since. It's been 2 weeks now

**Comment by ammoradi** [comment] 2023-09-04 08:19
> I am currently facing the same issue using react **17.0.2**. I have tried to reproduce it in CodeSandbox but the issue didn't appear there! From my small investigation it seems like the issue is `yarn`. @iamhosseindhv I have created a reproduction repository [bibixx/notistack-issue-485](https://github.com/bibixx/notistack-issue-485) that uses `yarn` (also there's a branch using `npm` where the whole thing seems to work just fine)
> 
> For the quick patch you can create a `.d.ts` file (like `notistack.d.ts`) and augment the module with:
> 
> ```ts
> import { SnackbarProvider as SnackbarProviderBase } from 'notistack';
> 
> declare module 'notistack' {
>   export interface SnackbarProvider extends SnackbarProviderBase {
>     render(): ReactNode;
>   }
> }
> ```
> 
> P.S. I believe CodeSandbox uses `npm` underneath so that's why we couldn't reproduce it there

I could fix the issue for my case in a bit different way:

```typescript
import { Component, ReactNode } from 'react';
import { SnackbarProviderProps } from 'notistack';

declare module 'notistack' {
  export interface SnackbarProvider extends Component<SnackbarProviderProps> {
    render(): ReactNode;
  }
}
```
