### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by viclafouch** [iamhosseindhv/notistack#345] opened 2020-12-30 14:13 UTC
## Expected Behavior

I've just installed Notistack on my project in React 17. I followed the Getting Started and got this warning/error:

`index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here:`.

I would like to avoid removing the Strict Mode. 

![image](https://user-images.githubusercontent.com/23353836/103356473-427bab80-4ab1-11eb-9112-49351cd898d9.png)

## Steps to Reproduce

* Use Notistack in React 17 and Strict Mode.
```
<React.StrictMode>
  <SnackbarProvider>
    <App />
  <SnackbarProvider>
</React.StrictMode>
```

* Enqueue a notification

```
enqueueSnackbar('Erreur', {
  variant: 'error'
})
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.3  |
| React        |   17.0.1      |
| Browser      |   Chrome Version 87.0.4280.88 (Build officiel) (x86_64)      |
| etc.         |         |

**Comment by mhmtugur** [comment] 2021-01-09 11:59
same here

**Comment by ahmcho** [comment] 2021-01-25 08:35
I believe this is a Material UI bug, to be precise a bug in Transition component. I have the same problem with MUI Menu component and after browsing came to conclusion that you either need to disable StrictMode or wait until it's fixed in the new version of Material UI. Here is the [discussion](https://stackoverflow.com/questions/61220424/material-ui-drawer-finddomnode-is-deprecated-in-strictmode).

**Comment by chrisrrowland** [comment] 2021-03-29 19:39
Is it possible to disable the transition in the notistack config until this is fixed?

**Comment by raphaelsoul** [comment] 2021-04-15 06:24
```
ReactDOM.render(
  <React.StrictMode> // remove me
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>, // remove me
  document.getElementById('root'),
);
```

this will prevent printing this warn. But be aware of that strict mode helps you find many potential problems. You'd better enable it at least in development

**Comment by iamhosseindhv** [comment] 2021-07-14 01:20
Duplicate of #257

**Closed by iamhosseindhv** 2021-07-14 01:20 UTC

**Comment by bobzhang123456** [comment] 2021-09-12 08:09
This is a temporary solution. 

ReactDOM.render(
  <NotistackProvider>
    <React.StrictMode>
          <App />
    </React.StrictMode>
  </NotistackProvider>,
  document.getElementById("root")
);
