### ISSUE TITLE
Custom variant don't work anymore

### ISSUE THREAD

**Issue by joepsyko** [iamhosseindhv/notistack#305] opened 2020-08-31 18:56 UTC
The following code was working before version 1.0.0.

```
const styles = {
    success: { backgroundColor: 'purple' },
    error: { backgroundColor: 'blue' },
    warning: { backgroundColor: 'green' },
    info: { backgroundColor: 'yellow' },
};


<SnackbarProvider
    classes={{
        variantSuccess: classes.success,
        variantError: classes.error,
        variantWarning: classes.warning,
        variantInfo: classes.info,
    }}
>
    <App />
</SnackbarProvider>
```

To make it work I have to add "!important" after the colour property:
```
success: { backgroundColor: 'purple !important' }
```
Is this a bug?

**Comment by parveen1112** [comment] 2020-09-01 18:05
Yes, I am also facing the same issue and had to use. Important to make it work.

**Comment by diospada** [comment] 2020-09-02 07:56
Please look at https://github.com/iamhosseindhv/notistack/pull/297

**Comment by joepsyko** [comment] 2020-09-02 11:25
> Please look at #297

I think we are talking about two different things, I found that code in the documentation and it was working before version 1.0.0. Now it doesn't work anymore so I think there is a regression/bug.

In this commit you can see that "!important" was added in the default colours:
https://github.com/iamhosseindhv/notistack/pull/297/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by parveen1112** [comment] 2020-09-02 13:04
I agree with @joepsyko. 

If I go the documentation 
https://iamhosseindhv.com/notistack/demos#custom-variants
I am not able to use this as shown. I have to mark backgroundColor or color as important.

Any specific reason for marking this important ?

```variantSuccess: {
            backgroundColor: '#43a047 !important', // green
            color: '#fff !important',
        },
        variantError: {
            backgroundColor: '#d32f2f !important', // dark red
            color: '#fff !important',
        },
        variantInfo: {
            backgroundColor: '#2196f3 !important', // nice blue
            color: '#fff !important',
        },
        variantWarning: {
            backgroundColor: '#ff9800 !important', // amber
            color: '#fff !important',
        },
```

**Comment by iamhosseindhv** [comment] 2020-09-02 20:56
I have tested locally, but reverting https://github.com/iamhosseindhv/notistack/pull/297/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e and removing `!important` from styles doesn't fix the problem. We still have to pass `!important` to override styles.

Happy to quickly publish a patch if anyone investigates and comes up with a PR. But for now overriding using `!important` is the solution.

**Comment by SimonAmphora** [comment] 2020-09-29 12:23
However, I'm facing the same issue where my new styles are not taking effect due to the !important flag in the snackbarItem styles:
```
.SnackbarItem-variantSuccess-380 {
    color: #fff !important;
    background-color: #43a047 !important;
}
```
you can see an example here:
https://codesandbox.io/s/nice-kapitsa-0k7go?file=/SnackbarProvider2.js
The top row of buttons is using standard styles, the second row is using styles with !important

**Comment by iamhosseindhv** [comment] 2020-10-06 17:37
This is regression and can be fixed by adding `!important`. I'm happy to apply a fix if someone is willing to dig more into it.

**Closed by iamhosseindhv** 2020-10-06 17:37 UTC

**Comment by fveauvy** [comment] 2020-11-11 18:04
> This is regression and can be fixed by adding `!important`. I'm happy to apply a fix if someone is willing to dig more into it.

Could it be added to the documentation ?

**Comment by iamhosseindhv** [comment] 2021-05-19 19:42
As of `v1.0.9`, you do not need to use !important anymore.
