### ISSUE TITLE
Not able to update content / update custom content using key

### ISSUE THREAD

**Issue by Sandeep0695** [iamhosseindhv/notistack#278] opened 2020-05-21 20:24 UTC
## Expected Behavior

    Toast content or custom content should be  updateable via key. 

## Current Behavior

    Don't have any this kind of features

**Comment by iamhosseindhv** [comment] 2020-05-22 10:05
Duplicate of # 234

**Closed by iamhosseindhv** 2020-05-22 10:05 UTC

**Comment by Sandeep0695** [comment] 2020-05-24 08:31
When it will be implement? ❓😔
